### ISSUE TITLE
Command injection - 🏓

### ISSUE THREAD

**Issue by AAA97AAA** [xavierpantet/my_ass_on_your_grass#11]
In the following file, we can see that when giving a specific command, we are able to open a calculator on the server side:

https://github.com/xavierpantet/my_ass_on_your_grass/blob/5ebeb6c98d689621444de3275847f134462da9b7/src/commands/Commands.cpp#L396-L411

**Solution:** Do not recruit engineers with great sense of humour! :)

Here's the input I gave to your client program:
`ping pong`

**Comment by xavierpantet** [comment]
Hahaha 😂 
Thank you for reporting the issue. I close this one because it is a duplicate of #1.
